AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
    - vendor/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/OptionalBooleanParameter:
  Enabled: false
