language: ruby
dist: xenial
os: linux
cache: bundler

rvm:
  - 2.6.3
  - 2.6.6
  - 2.7.0
  - 2.7.1
  - 2.7.2

before_install: gem install bundler -v 1.17.3
install: bundle _1.17.3_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

branches:
  only:
    - main
    - master
