name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  default:
  strategy:
    matrix:
      ruby: [2.6.3, 2.6.6, 2.7.0, 2.7.2]
    runs-on: ubuntu-latest
    fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rake
