name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6.3, 2.6.6, 2.7.0, 2.7.2]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 1.17.3
        bundler-cache: true
    - run: bundle exec rake
  pronto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: HeRoMo/pronto-action@v1.13.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
