name: Scheduled
on:
  schedule:
    - cron: "0 4 * * 1" # 4am UTC on Mondays (10pm/11pm CT on Sundays)
  # These are for temporary testing
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundler-audit:
    if:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler: 1.17.3
        bundler-cache: true
    - run: bash .github/bundler_audit \
        ${{ github.REPOSITORY }} ${{ github.RUN_ID }} \
        ${{ secrets.SLACK_ALERTS_CHANNEL }} ${{ secrets.SLACK_WEBHOOK_URL }}
  bundle-outdated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler: 1.17.3
        bundler-cache: true
    - run: bash .github/bundle_outdated \
        ${{ github.REPOSITORY }} ${{ github.RUN_ID }} \
        ${{ secrets.SLACK_ALERTS_CHANNEL }} ${{ secrets.SLACK_WEBHOOK_URL }}
